# Generated by Django 3.2.15 on 2022-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('birthday', models.DateField(null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
    ]
